### PR TITLE
Added support for 'Drag and Drop'

### PR DESCRIPTION
**Pull request by JohnnyCrazy**
Just implemented Drag and Drop, Size of the Controls got changed a bit, but it's no difference at all.

### CODE REVIEW

**Comment by whisperity** [comment]
Definitely thanks for the changes :gift: ! :smile:

By drag'n'drop, I meant the functionality of the _Add file_ button. But I have an idea. I will pull your changes in, and the DragDrop functionality of the ListView will act that if a GMA is dropped, it will be loaded, and if another file is dropped, it will, at least, tried to be added.

Will look into this soon.

**Comment by JohnnyCrazy** [comment]
Yea that would be cool :+1: 

Didn't think of using the Drag-and-Drop function to import Files :smile:

**Comment by whisperity** [comment]
Well, thanks for the code once again. I have modified it slightly so it supports both file-adding and loading other GMAs.
After that, I thought directory support would be a wonderful thing if directories can be drag'n'dropped into the program as well.

**Comment by JohnnyCrazy** [comment]
Okay, glad i could help. :smile: 

If i can help you with anything related to the software, just message me

**Pull request closed without merging**
