### PR TITLE
Fix for Issue 8

### PR DESCRIPTION
**Pull request by JohnnyCrazy**
This is a proper fix for #8.

If a gma is locked, prompt the user if he wants to open it in ReadOnly Mode. In ReadOnly Mode, all buttons, which would write sth into the stream, will be disabled (but visible :smile:).

ReadOnly opens the FileStream with just Read-Access.
( I didn't know, if we should grant FileShare permissions, since Gmod could interrupt it somehow, need some further investigation on this)

If you want to change something, feel free to do so :smiley: 
Johnny

### CODE REVIEW

**Comment by whisperity** [comment]
The approach looks fine at first glance, but you should not change the `.Enabled` directly to `canWrite`. It should be something like `true && canWrite`. (Where it should be `false`, this is not needed because it's false/disabled no matter what.)

**Comment by JohnnyCrazy** [comment]
but true && canWrite would return the same boolean as canWrite wouldn't it?

So you would like an If-clause before setting the button's disable/enable?

**Comment by whisperity** [comment]
> Damn first grade maths. :smirk:

Sorry, my brain was really underclocked on this as I was at work (and was looking at the code on GitHub, not in VS).

I will make a few changes here and there, especially for _realtime commandline_, and merge it. Thanks.

**Comment by JohnnyCrazy** [comment]
No problem, hope i helped you a bit :smiley:

**Comment by whisperity** [comment]
Okay I found out what I was meaning to say on my comment. The same approach, but I pinpointed the wrong line.
So here's how it should've been:

``` c#
if (canWrite)
  tsmFilePull.Enabled = isExported.First().Modified;
else
  tsmFilePull.Enabled = false;
```

This line of code will be shortened into `tsmFilePull.Enabled = canWrite && isExported.First().Modified;` This is what I wanted to say instead of that idiotic `true && canWrite` stuff.

**Comment by JohnnyCrazy** [comment]
Ah okay, yea that makes sense,

Did you already implement it or should I do the commit?

**Comment by whisperity** [comment]
I've already implemented it. :smile:

**Comment by JohnnyCrazy** [comment]
Alright :smiley:

**Pull request merged**
